### ISSUE TITLE
branch-2.0 cannot build on Ubuntu 16.04

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2595]
When we build .deb for Ubuntu 16.04 using ./dist/debian/build_deb.sh, it fails when building dpdk related code:
```
FAILED: g++ -MD -MT build/release/net/dpdk.o -MF build/release/net/dpdk.o.d -O2 -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/release/gen -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar -U_FORTIFY_SOURCE  -march=nehalem -DHAVE_DPDK -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -DFMT_HEADER_ONLY -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/net/dpdk.o net/dpdk.cc
In file included from net/dpdk.cc:43:0:
/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/core/dpdk_rte.hh:25:24: fatal error: rte_ethdev.h: No such file or directory
compilation terminated.
FAILED: g++ -MD -MT build/release/core/dpdk_rte.o -MF build/release/core/dpdk_rte.o.d -O2 -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/release/gen -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar -U_FORTIFY_SOURCE  -march=nehalem -DHAVE_DPDK -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -DFMT_HEADER_ONLY -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/core/dpdk_rte.o core/dpdk_rte.cc
In file included from core/dpdk_rte.cc:22:0:
/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/core/dpdk_rte.hh:25:24: fatal error: rte_ethdev.h: No such file or directory
compilation terminated.
FAILED: g++ -MD -MT build/release/core/reactor.o -MF build/release/core/reactor.o.d -O2 -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/release/gen -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar -U_FORTIFY_SOURCE  -march=nehalem -DHAVE_DPDK -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -I/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -DFMT_HEADER_ONLY -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/core/reactor.o core/reactor.cc
In file included from core/reactor.cc:66:0:
/build/scylla-server-2.0~rc0-0.20170712.a371b8a/seastar/core/dpdk_rte.hh:25:24: fatal error: rte_ethdev.h: No such file or directory
compilation terminated.
```

And it's not happens on master branch.

**Comment by syuu1228** [comment]
I found that this is because our package versioning.
VERSION=2.0.rc0 will extract to something like: 
```
/build/scylla-server-2.0~rc0-0.20170712.a371b8a
```
So the build directory contains tilde, but DPDK does not able to compile in the path that contains tilde.

While the build path contains tilde, ROOTDIRS-y on https://github.com/scylladb/dpdk/blob/local-17.02/mk/rte.sdkdepdirs.mk#L39 become empty.
Therefore DEPDIR_FILES empty too, 'make depdirs' cannot succeed.
So it's looks like DPDK Makefile bug, but easily avoid it by change versioning scheme to 2.0-rcX.

**Comment by argenet** [comment]
Just FYI, while trying to upgrade DPDK to 17.05 I tried building ScyllaDB 2.0rc4 .deb package with DPDK on Ubuntu 16.04 and it worked fine without the fix above.
Looks like the issue has gone in the mainstream repository with the patch http://www.dpdk.org/browse/dpdk/commit/?id=feb9f680cd2c1df3d47bf4c05dc872467176e1e3 

Here is the build log: https://gist.github.com/argenet/69e895427c3862d622eb2ed4a58c19ec 

So, this fix doesn't need to be forward-ported when upgrading Seastar DPDK.
