### ISSUE TITLE
`TimeWindowCompactionStrategy` not using specialized reader for single partition queries

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#8415]
1. create a TWCS table
2. perform a single partition query

`time_series_sstable_set::create_single_key_sstable_reader` is not called.
(checked using "printf debugging").
Therefore the optimization introduced in PR #7437 is never used.

Investigation leads to the following conclusion: the `time_series_sstable_set` is wrapped into a recently introduced `compound_sstable_set`,  but `compound_sstable_set` does not implement `create_single_key_sstable_reader`, causing the generic version to be called instead of the specialized one.

cc @raphaelsc

**Comment by raphaelsc** [comment]
will fix. thanks for reporting
