### PR TITLE
Update seastar submodule

### LINKED ISSUE #26925: seastar_memory - oversized allocation: 327680 bytes (std::deque<seastar::do_recursive_remove_directory ?)
## Packages

Scylla version: `2026.1.0~dev-20251107.cdba3bebdaf5` with build-id `0ab26de3266d5879cca02328a948c4e54dfa4fb6`

Kernel Version: `6.14.0-1016-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

```
2025-11-08 14:32:53.955 <2025-11-08 14:32:53.230>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=560cd1f4-a5ed-4229-bf09-da62a051e3d1: type=OVERSIZED_ALLOCATION regex=seastar_memory - oversized allocation: line_number=1801700 node=longevity-twcs-3h-master-db-node-74b06743-1
2025-11-08T14:32:53.230 longevity-twcs-3h-master-db-node-74b06743-1 !WARNING | scylla[39200]  [shard 0:strm] seastar_memory - oversized allocation: 327680 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at 0x2627789 0x2627340 0x1bbaee8 0x28814a7 0x1993b50 0x58a6c86 0x58a832e 0x58a80c9 0x574994b 0x5749db8 0x574aed8 0x15ce128 0x32c1078 0x32c0889 0x32c02e3 0x32bdd57 0x32b9ce2 /opt/scylladb/libreloc/libc.so.6+0x3574 /opt/scylladb/libreloc/libc.so.6+0x3627 0x359a134
seastar::current_backtrace_tasklocal() at backtrace.cc:?
seastar::current_tasktrace() at backtrace.cc:?
seastar::current_backtrace() at backtrace.cc:?
seastar::memory::cpu_pages::warn_large_allocation(unsigned long) at memory.cc:?
seastar::memory::allocate_slowpath(unsigned long) at memory.cc:?
std::deque<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry, std::allocator<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry> >::_M_reserve_map_at_back(unsigned long) at file.cc:?
seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry& std::deque<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry, std::allocator<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry> >::emplace_back<std::filesystem::__cxx11::path const, bool>(std::filesystem::__cxx11::path const&&, bool&&) at file.cc:?
std::_Function_handler<seastar::future<void> (seastar::directory_entry), seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::$_0::operator()<std::deque<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry, std::allocator<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry> > >(std::deque<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry, std::allocator<seastar::do_recursive_remove_directory(std::filesystem::__cxx11::path)::work_entry> >&)::{lambda()#2}::operator()()::{lambda(std::filesystem::__cxx11::path const&)#1}::operator()(std::filesystem::__cxx11::path const&) const::{lambda(seastar::file)#1}::operator()(seastar::file)::{lambda(seastar::file&)#1}::operator()(seastar::file&)::{lambda(seastar::directory_entry)#1}>::_M_invoke(std::_Any_data const&, seastar::directory_entry&&) at file.cc:?
seastar::noncopyable_function<seastar::future<void> (seastar::directory_entry)>::direct_vtable_for<std::function<seastar::future<void> (seastar::directory_entry)> >::call(seastar::noncopyable_function<seastar::future<void> (seastar::directory_entry)> const*, seastar::directory_entry) at file.cc:?
seastar::posix_file_impl::list_directory(std::function<seastar::future<void> (seastar::directory_entry)>)::$_0::operator()() const::{lambda()#2}::operator()() const at file.cc:?
seastar::internal::do_until_state<seastar::posix_file_impl::list_directory(std::function<seastar::future<void> (seastar::directory_entry)>)::$_0::operator()() const::{lambda()#1}, seastar::posix_file_impl::list_directory(std::function<seastar::future<void> (seastar::directory_entry)>)::$_0::operator()() const::{lambda()#2}>::run_and_dispose() at file.cc:?
seastar::reactor::do_run() at reactor.cc:?
seastar::reactor::run() at reactor.cc:?
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at app-template.cc:?
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at app-template.cc:?
scylla_main(int, char**) at main.cc:?
main at ??:?
?? ??:0
?? ??:0
_start at ??:?
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.2xlarge)

Scylla Nodes used in this run:

    - longevity-twcs-3h-master-db-node-74b06743-9 (34.253.182.62 | 10.4.9.146) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-8 (3.254.68.176 | 10.4.9.242) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-7 (3.255.153.19 | 10.4.9.119) (shards: -1)

    - longevity-twcs-3h-master-db-node-74b06743-6 (3.253.85.251 | 10.4.9.158) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-5 (3.254.97.95 | 10.4.9.89) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-4 (108.130.43.230 | 10.4.11.240) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-3 (52.212.37.24 | 10.4.9.68) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-2 (52.18.98.201 | 10.4.11.21) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-13 (3.249.126.207 | 10.4.9.199) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-12 (34.254.203.73 | 10.4.8.190) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-11 (18.201.152.45 | 10.4.9.185) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-10 (3.255.175.132 | 10.4.10.61) (shards: 7)

    - longevity-twcs-3h-master-db-node-74b06743-1 (54.170.200.39 | 10.4.8.183) (shards: -1)

OS / Image: `ami-0b05c513b8d118959` (aws: N/A)

Test: `longevity-twcs-2h-rackaware-test`
Test id: `74b06743-47be-463b-9e98-47aac1266000`
Test name: `scylla-master/longevity/longevity-twcs-2h-rackaware-test`

    Test method: `longevity_twcs_test.TWCSLongevityTest.test_twcs_longevity`

Test config file(s):

- [longevity-twcs-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/e459655063431b4e203f18e015c6fc86c902e455/test-cases/longevity/longevity-twcs-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 74b06743-47be-463b-9e98-47aac1266000`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=74b06743-47be-463b-9e98-47aac1266000)
- Show all stored logs command: `$ hydra investigate show-logs 74b06743-47be-463b-9e98-47aac1266000`

## Logs:

- **[longevity-twcs-3h-master-db-node-74b06743-6](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-6/download)**

- **[longevity-twcs-3h-master-db-node-74b06743-5](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-5/download)**

- **[longevity-twcs-3h-master-db-node-74b06743-4](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-4/download)**

- **[longevity-twcs-3h-master-db-node-74b06743-8](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-8/download)**

- **[longevity-twcs-3h-master-db-node-74b06743-7](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-7/download)**

- **[longevity-twcs-3h-master-db-node-74b06743-3](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-3/download)**

- **[longevity-twcs-3h-master-db-node-74b06743-10](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-10/download)**

- **[longevity-twcs-3h-master-db-node-74b06743-2](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/longevity-twcs-3h-master-db-node-74b06743-2/download)**

- **[db-cluster-74b06743.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/db-cluster-74b06743.tar.zst/download)**

- **[schema-logs-74b06743.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/schema-logs-74b06743.tar.zst/download)**

- **[sct-runner-events-74b06743.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/sct-runner-events-74b06743.tar.zst/download)**

- **[2025_11_08__04_07_59_089.sct-74b06743.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/2025_11_08__04_07_59_089.sct-74b06743.log.zst/download)**

- **[2025_11_08__09_40_19_357.sct-74b06743.log.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/2025_11_08__09_40_19_357.sct-74b06743.log.zst/download)**

- **[loader-set-74b06743.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/loader-set-74b06743.tar.zst/download)**

- **[monitor-set-74b06743.tar.zst](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/monitor-set-74b06743.tar.zst/download)**

- **[builder-74b06743.log.tar.gz](https://argus.scylladb.com/api/v1/tests/scylla-cluster-tests/74b06743-47be-463b-9e98-47aac1266000/log/builder-74b06743.log.tar.gz/download)**

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-2h-rackaware-test/17/)
[Argus](https://argus.scylladb.com/test/f379dbf3-c372-450d-9974-619140ca8457/runs?additionalRuns[]=74b06743-47be-463b-9e98-47aac1266000)
</details>

### PR DESCRIPTION
**Pull request by avikivity**
* seastar 63900e030...a00e7a248 (25):
  > metrics: Remove deprecated make_...-ers
  > Merge 'Make slab_test be BOOST kind' from Pavel Emelyanov
  > Merge 'Coroutinize lister_test' from Pavel Emelyanov
  > file: recursive_remove_directory(): use a list instead of a deque
  > Merge 'Stop using packets in tls data_sink and session' from Pavel Emelyanov
  > github: disable AVX2 instruction set when building dpdk
  > Merge 'rpc: harden sink_impl::close()' from Benny Halevy
  > http: Document the way "unread body bytes" accounting works
  > net: tighten port load balancing port access
  > coroutine: reimplement generator with buffered variant
  > Merge 'Stop using net::packet in posix data sink' from Pavel Emelyanov
  > Merge 'Generalize memory data sink in tests' from Pavel Emelyanov
  > dns: avoid using deprecated c-ares API
  > reactor: Move read_directory() to posix_file_impl
  > Merge 'rpc: sink_impl: batch sending and deletion of snd_buf:s' from Benny Halevy
  > configure.py: fix --api-level help
  > Merge 'Close http client connection if handler doesn't consume all chunked-encoded body' from Pavel Emelyanov
  > metrics: Add default ~config()
  > headers: Remove smp.hh from app-template.hh
  > prometheus: remove hostname and metric_help config
  > rpc: Tune up connection methods visibility
  > perf_tests: Fix build with fmt 12.0.0 by avoiding internal functions
  > doc: Fix some typos in codying style
  > reactor: Remove unused try_sleep() method
  > memory.cc: compile fix for std::bit_width()

Fixes #26925

Routine Seastar update. The bug fixed is minor and not a regression, so does not deserve a backport.

### CODE REVIEW

**Comment by avikivity** [comment]
Looks like spot termination, but not reported.

@scylladbbot trigger-ci please

**Comment by avikivity** [comment]
@yaronkaikov it looks stuck

**Comment by yaronkaikov** [comment]
> Looks like spot termination, but not reported.
> 
> @scylladbbot trigger-ci please

it's not :-), you can use the link to get into the Jenkins Job and it's seems to be running

**Comment by avikivity** [comment]
> it's not :-), you can use the link to get into the Jenkins Job and it's seems to be running

Yes thanks.

**Comment by avikivity** [comment]
```
23:12:31  utils/lister.cc:108:22: error: cannot refer to type member 'type' in 'std::reference_wrapper<seastar::directory_entry>' with '->'
23:12:31    108 |             if (!de->type) {
23:12:31        |                      ^
23:12:31  /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/refwrap.h:329:19: note: member 'type' declared here
23:12:31    329 |       typedef _Tp type;
23:12:31        |                   ^
23:12:31  utils/lister.cc:109:21: error: cannot refer to type member 'type' in 'std::reference_wrapper<seastar::directory_entry>' with '->'
23:12:31    109 |                 de->type = co_await file_type((_dir / de->name).native(), follow_symlink::no);
23:12:31        |                     ^
23:12:31  /usr/lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/bits/refwrap.h:329:19: note: member 'type' declared here
```

@xemul did we break the lister?

**Comment by xemul** [comment]
It's experimental lister, just like coroutine generator still is. So instead of returning `std::optional<directory_entry>` it now returns `std::optional<std::reference_wrapper<directory_entry>>` and needs two "dereferences" like in https://github.com/scylladb/seastar/commit/81f2dc9dd976b0019ff84274b8b7fb7507c3e4e7:

```patch
@@ -92,14 +93,16 @@ SEASTAR_TEST_CASE(test_lister) {
 
 future<> lister_generator_test(file f) {
     auto lister = f.experimental_list_directory();
+
     while (auto de = co_await lister()) {
-        auto sd = co_await file_stat(de->name, follow_symlink::no);
-        if (de->type) {
-            SEASTAR_ASSERT(*de->type == sd.type);
+        auto& entry = de->get();                                    // <<<<<<<<<<<<<<<<<<<<<<<<<< HERE
+        auto sd = co_await file_stat(entry.name, follow_symlink::no);
+        if (entry.type) {
+            SEASTAR_ASSERT(entry.type == sd.type);
         } else {
             SEASTAR_ASSERT(sd.type == directory_entry_type::unknown);
         }
-        fmt::print("{} (type={})\n", de->name, de_type_desc(sd.type));
+        fmt::print("{} (type={})\n", entry.name, de_type_desc(sd.type));
     }
     co_await f.close();
 }
```

**Comment by xemul** [comment]
Benny did it here: https://github.com/scylladb/scylladb/pull/26913/commits/ffcd245a19b3ffd0e275ffddc7227db049aa47db

**Comment by xemul** [comment]
@avikivity , I also encourage you to use `scripts/refresh-submodules.sh`, it generates nicer summary for the update comment (#24834)

**Comment by avikivity** [comment]
> Benny did it here: [ffcd245](https://github.com/scylladb/scylladb/commit/ffcd245a19b3ffd0e275ffddc7227db049aa47db)

Maybe the output is nicer, but there's no explanations to the code changes.

Did we break lister? We shouldn't break seastar APIs.

**Comment by avikivity** [comment]
https://github.com/scylladb/scylladb/pull/27065

Why is there a different number of commits?

**Comment by xemul** [comment]
> Did we break lister? We shouldn't break seastar APIs.

It's experimental API that's allowed to get broken at times. It's the generator API that was "broken" and since lister was using generator API, it got broken as well

**Comment by xemul** [comment]
> Why is there a different number of commits?

What do you mean?

There are 3 commits in the change
```
$ git shortlog 19445a5...2240122
Avi Kivity (1):
      copyutil: adjust multiprocessing method to 'fork'

Dmitry Kropachev (1):
      Drop serverless/cloudconf feature

blacksmith-sh[bot] (1):
      Migrate workflows to Blacksmith
```

and 3 in the update commit message

```
 Update tools/cqlsh submodule

* tools/cqlsh 19445a5...2240122 (3):
  > copyutil: adjust multiprocessing method to 'fork'
  > Drop serverless/cloudconf feature
  > Migrate workflows to Blacksmith
```

**Comment by avikivity** [comment]
> > Why is there a different number of commits?
> 
> What do you mean?
> 
> There are 3 commits in the change
> 
> ```
> $ git shortlog 19445a5...2240122
> Avi Kivity (1):
>       copyutil: adjust multiprocessing method to 'fork'
> 
> Dmitry Kropachev (1):
>       Drop serverless/cloudconf feature
> 
> blacksmith-sh[bot] (1):
>       Migrate workflows to Blacksmith
> ```
> 
> and 3 in the update commit message
> 
> ```
>  Update tools/cqlsh submodule
> 
> * tools/cqlsh 19445a5...2240122 (3):
>   > copyutil: adjust multiprocessing method to 'fork'
>   > Drop serverless/cloudconf feature
>   > Migrate workflows to Blacksmith
> ```

I think I attached the comment to the wrong pull request.

There are two competing "update cqlsh submodue" pull requests, with two and three commits.

**Comment by avikivity** [comment]
> > Did we break lister? We shouldn't break seastar APIs.
> 
> It's experimental API that's allowed to get broken at times. It's the generator API that was "broken" and since lister was using generator API, it got broken as well

Right.

**Comment by avikivity** [comment]
> It's experimental lister, just like coroutine generator still is. So instead of returning `std::optional<directory_entry>` it now returns `std::optional<std::reference_wrapper<directory_entry>>` and needs two "dereferences" like in 

Ah. In C++26 we have std::optional\<T&>.

Can we make the return type nicer? Return std::optional\<directory_entry>& perhaps?


[scylladb/seastar@81f2dc9](https://github.com/scylladb/seastar/commit/81f2dc9dd976b0019ff84274b8b7fb7507c3e4e7):
> 
> ```diff
> @@ -92,14 +93,16 @@ SEASTAR_TEST_CASE(test_lister) {
>  
>  future<> lister_generator_test(file f) {
>      auto lister = f.experimental_list_directory();
> +
>      while (auto de = co_await lister()) {
> -        auto sd = co_await file_stat(de->name, follow_symlink::no);
> -        if (de->type) {
> -            SEASTAR_ASSERT(*de->type == sd.type);
> +        auto& entry = de->get();                                    // <<<<<<<<<<<<<<<<<<<<<<<<<< HERE
> +        auto sd = co_await file_stat(entry.name, follow_symlink::no);
> +        if (entry.type) {
> +            SEASTAR_ASSERT(entry.type == sd.type);
>          } else {
>              SEASTAR_ASSERT(sd.type == directory_entry_type::unknown);
>          }
> -        fmt::print("{} (type={})\n", de->name, de_type_desc(sd.type));
> +        fmt::print("{} (type={})\n", entry.name, de_type_desc(sd.type));
>      }
>      co_await f.close();
>  }
> ```

**Comment by xemul** [comment]
>  Return std::optional<directory_entry>& perhaps?

It would mean copying a value from generator context inside the optional, now it doesn't, but sets up a reference inside optional

> Ah. In C++26 we have std::optional<T&>.

Optional reference is called pointer, and now I wonder why new generator returns optional<reference_wrapper> instead of a pointer either

**Comment by avikivity** [comment]
Obsoleted by 8ed36702aecead9b71260d0ab93e037b7895b757

**Comment by xemul** [comment]
> * a00e7a248

@avikivity , it's not, this PR was supposed to carry scylladb/seastar@c1493b09bf0693ed28d194fd70bd6675d2361542, but the update you pointed to didn't do it

**Comment by avikivity** [comment]
Well, it will be obsoleted by something, I hope.
