### PR TITLE
service/CMakeLists.txt: Add cql3 as private library

### PR DESCRIPTION
**Pull request by dawmd**
Before these changes, trying to compile Scylla with CMake fails with the following message:

```
In file included from $HOME/src/scylla/service/qos/service_level_controller.cc:9:
$HOME/src/scylla/cql3/util.hh:21:10: fatal error: 'cql3/CqlParser.hpp' file not found
   21 | #include "cql3/CqlParser.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Said file is auto-generated and we need to indicate the dependency in the appropriate CMake file.
That's what we do in this commit.

Fixes scylladb/scylladb#20821

Backport: not needed as the offending commit didn't make it to the previous versions.

### CODE REVIEW

**Comment by tchaikov** [comment]
@dawmd hi Dawid, thank you for creating the fix with the detailed commit message, but we already have #20805 created by Lakshmi, which was created 15 hours ago before your pull request. so i'd prefer using his change. unfortunately, we've expereienced a couple unrelated test failures, so the merge was blocked.

**Comment by tchaikov** [comment]
#20805 has been queued. i am closing this PR. thank you again, Dawid, for the prompt fix!

**Comment by lersek** [comment]
Indeed, thank you Dawid!
