### ISSUE TITLE
Build fails when configured to not use precompiled headers

### ISSUE THREAD

**Issue by emdroid** [scylladb/scylla#28378]
When the scylla build is configured without precompiled headers, for example:
```bash
./configure.py --disable-dpdk --compiler-cache=ccache --disable-precompiled-header
```

The build (e.g. "`ninja build/dev/scylla`") then fails with:

```
db/view/view.cc:2690:14: error: no member named 'all' in namespace 'seastar::coroutine'; did you mean 'experimental_features_t::all'?
 2690 |     co_await coroutine::all(
      |              ^~~~~~~~~~~~~~
      |              experimental_features_t::all
./db/config.hh:122:62: note: 'experimental_features_t::all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
db/view/view.cc:2691:9: error: too many arguments to function call, expected 0, have 2
 2690 |     co_await coroutine::all(
      |              ~~~~~~~~~~~~~~
 2691 |         [this, ks_name, view_name, units = std::move(units)] mutable -> future<> {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2692 |             co_await handle_create_view_local(ks_name, view_name, std::move(units)); },
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2693 |         [this, ks_name, view_name] mutable -> future<> {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2694 |             co_await container().invoke_on_others([ks_name = std::move(ks_name), view_name = std::move(view_name)] (view_builder& vb) mutable -> future<> {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2695 |                 return vb.handle_create_view_local(ks_name, view_name, std::nullopt); }); });
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./db/config.hh:122:62: note: 'all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
db/view/view.cc:2709:18: error: no member named 'all' in namespace 'seastar::coroutine'; did you mean 'experimental_features_t::all'?
 2709 |         co_await coroutine::all(
      |                  ^~~~~~~~~~~~~~
      |                  experimental_features_t::all
./db/config.hh:122:62: note: 'experimental_features_t::all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
db/view/view.cc:2710:13: error: too many arguments to function call, expected 0, have 2
 2709 |         co_await coroutine::all(
      |                  ~~~~~~~~~~~~~~
 2710 |             [&step] -> future<> {
      |             ^~~~~~~~~~~~~~~~~~~~~
 2711 |                 co_await step.base->await_pending_writes(); },
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2712 |             [&step] -> future<> {
      |             ~~~~~~~~~~~~~~~~~~~~~
 2713 |                 co_await step.base->await_pending_streams(); });
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./db/config.hh:122:62: note: 'all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
db/view/view.cc:2773:14: error: no member named 'all' in namespace 'seastar::coroutine'; did you mean 'experimental_features_t::all'?
 2773 |     co_await coroutine::all(
      |              ^~~~~~~~~~~~~~
      |              experimental_features_t::all
./db/config.hh:122:62: note: 'experimental_features_t::all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
db/view/view.cc:2774:9: error: too many arguments to function call, expected 0, have 2
 2773 |     co_await coroutine::all(
      |              ~~~~~~~~~~~~~~
 2774 |         [this, ks_name, view_name, units = std::move(units)] mutable -> future<> {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2775 |             co_await handle_drop_view_local(ks_name, view_name, std::move(units)); },
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2776 |         [this, ks_name, view_name] mutable -> future<> {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2777 |             co_await container().invoke_on_others([ks_name = std::move(ks_name), view_name = std::move(view_name)] (view_builder& vb) mutable -> future<> {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2778 |                 return vb.handle_drop_view_local(ks_name, view_name, std::nullopt); });});
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./db/config.hh:122:62: note: 'all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
db/view/view.cc:2807:18: error: no member named 'all' in namespace 'seastar::coroutine'; did you mean 'experimental_features_t::all'?
 2807 |         co_await coroutine::all(
      |                  ^~~~~~~~~~~~~~
      |                  experimental_features_t::all
./db/config.hh:122:62: note: 'experimental_features_t::all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
db/view/view.cc:2808:13: error: too many arguments to function call, expected 0, have 3
 2807 |         co_await coroutine::all(
      |                  ~~~~~~~~~~~~~~
 2808 |             [this, &ks_name, &view_name] -> future<>  {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2809 |                 co_await _sys_ks.remove_view_build_progress_across_all_shards(ks_name, view_name); },
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2810 |             [this, &ks_name, &view_name] -> future<>  {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2811 |                 co_await _sys_ks.remove_built_view(ks_name, view_name); },
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2812 |             [this, &ks_name, &view_name] -> future<>  {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2813 |                 co_await remove_view_build_status(ks_name, view_name); });
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./db/config.hh:122:62: note: 'all' declared here
  122 |     static std::vector<enum_option<experimental_features_t>> all();
      |                                                              ^
8 errors generated.
ninja: build stopped: subcommand failed.
```

This breaks the build in such case. Looks like the "db/view/view.cc:" might be missing an include.

**Comment by emdroid** [comment]
It looks like this was introduced in https://github.com/scylladb/scylladb/pull/28093 (cc @calebxyz), I'll make a quick fix shortly.

It doesn't manifest when precompiled headers are used (which is the default), so that's probably why it was missed in the CI (I disabled precompiled headers locally because the build then behaves better wrt. ccache).

**Comment by calebxyz** [comment]
i see thats a shame we should really see that we will try at least to build it in both ways 
@yaronkaikov

**Comment by yaronkaikov** [comment]
> i see thats a shame we should really see that we will try at least to build it in both ways [@yaronkaikov](https://github.com/yaronkaikov)

If you tag me, you better have a question or request. otherwise i don't understand 😄

**Comment by avikivity** [comment]
Hmm. We should make `ninja dev-headers` avoid precompiled headers.

**Comment by emdroid** [comment]
@yaronkaikov The question is if we can also try a build without precompiled headers in the CI, so that we would catch issues like this during the PR merge check.

**Comment by calebxyz** [comment]
> > i see thats a shame we should really see that we will try at least to build it in both ways [@yaronkaikov](https://github.com/yaronkaikov)
> 
> If you tag me, you better have a question or request. otherwise i don't understand 😄

the request is to run builds without precompiled headers (sorry i thought the context is good :) )

**Comment by mykaul** [comment]
> > > i see thats a shame we should really see that we will try at least to build it in both ways [@yaronkaikov](https://github.com/yaronkaikov)
> > 
> > 
> > If you tag me, you better have a question or request. otherwise i don't understand 😄
> 
> the request is to run builds without precompiled headers (sorry i thought the context is good :) )

I would not add blindly 'yet-another-build-variant' to our pipeline. A nightly should be sufficient perhaps.

**Comment by calebxyz** [comment]
> I would not add blindly 'yet-another-build-variant' to our pipeline. A nightly should be sufficient perhaps.

i think its not good enough i dont want to push something that will break and we will only know about it at night , 
i suggest that the debug build will be without precompiled headers
