### ISSUE TITLE
boost/container/small_vector.hpp: No such file or directory on Ubuntu 14.04

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2903]
Seems like Ubuntu 14.04's boost-1.55 does not have container/small_vector.hpp, so we are not able to compile:
```
20:24:59 FAILED: g++-5 -MD -MT build/release/db/commitlog/commitlog_replayer.o -MF build/release/db/commitlog/commitlog_replayer.o.d -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/build/scylla-server-666.development-0.20171016.6d5a0f8/seastar -U_FORTIFY_SOURCE -I/opt/scylladb/include -L/opt/scylladb/lib -march=nehalem -DHAVE_DPDK -I/build/scylla-server-666.development-0.20171016.6d5a0f8/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -I/build/scylla-server-666.development-0.20171016.6d5a0f8/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -DFMT_HEADER_ONLY -DNO_EXCEPTION_HACK -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA -O2 -I/build/scylla-server-666.development-0.20171016.6d5a0f8/seastar/build/release/gen -I/build/scylla-server-666.development-0.20171016.6d5a0f8/seastar/build/release/c-ares -I/opt/scylladb/include -L/opt/scylladb/lib -I/usr/include/jsoncpp -DBOOST_TEST_DYN_LINK -Wno-maybe-uninitialized -Wno-missing-braces -Wno-error=deprecated-declarations  -I. -I build/release/gen -I seastar -I seastar/build/release/gen  -c -o build/release/db/commitlog/commitlog_replayer.o db/commitlog/commitlog_replayer.cc
20:24:59 In file included from ./sstables/disk_types.hh:25:0,
20:24:59                  from ./sstables/types.hh:24,
20:24:59                  from ./sstables/sstables.hh:37,
20:24:59                  from db/commitlog/commitlog_replayer.cc:54:
20:24:59 ./utils/chunked_vector.hh:29:44: fatal error: boost/container/small_vector.hpp: No such file or directory
20:24:59 compilation terminated.
```

```
# ls /usr/include/boost/container/
allocator_traits.hpp  list.hpp                  stable_vector.hpp
container_fwd.hpp     map.hpp                   static_vector.hpp
deque.hpp             scoped_allocator.hpp      string.hpp
detail                scoped_allocator_fwd.hpp  throw_exception.hpp
flat_map.hpp          set.hpp                   vector.hpp
flat_set.hpp          slist.hpp
```

**Comment by avikivity** [comment]
Let's compile with boost 1.63, do we already have it on that platform?

The alternative is 

```c++
#if __has_include(<boost/container/small_vector.hpp>)

#include <boost/container/small_vector.hpp>

template <typename T, size_t N>
using small_vector = boost::small_vector<T, N>;

#else

template <typename T, size_t N>
using small_vector = std::vector<T>;

#endif
```

**Comment by syuu1228** [comment]
@avikivity Tried build with boost-1.63 + gcc-5, but it seems boost header doesn't able to compile with the gcc version.
It can solve by using gcc-7, but I need little more work to make it ready on dist/debian/ build scripts.

**Comment by avikivity** [comment]
Let's wait until we have gcc 7 then, we want it anyway.
