### ISSUE TITLE
missing dead row marker in test_sstable_conforms_to_mutation_source

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8324]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3318/artifact/testlog/debug/sstable_conforms_to_mutation_source_test.20.log
But reproducible with `--random-seed=1869577008` in earlier versions.
```
$ build/release/test/boost/sstable_conforms_to_mutation_source_test --catch_system_errors=no --color_output=false -- -c 2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --default-log-level info --random-seed=1869577008 >& /tmp/sstable_conforms_to_mutation_source_test.out
```

```diff
$ ./test/lib/mutation_diff /tmp/sstable_conforms_to_mutation_source_test.out
--- /dev/fd/63	2021-03-21 09:38:49.428319005 +0200
+++ /dev/fd/62	2021-03-21 09:38:49.429319002 +0200
@@ -1,4 +1,4 @@
-test/lib/mutation_assertions.hh(108): fatal error: in "test_sstable_conforms_to_mutation_source": Mutations differ, expected 
+ ...but got: 
 {table: 'ks.cf', key: {'pk': 1806000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, token: -9205109811216406580}, mutation_partition: {
   tombstone: {tombstone: timestamp=-9223372036854775805, deletion_time=2},
   range_tombstones: {
@@ -81,7 +81,6 @@
     {
       cont: true,
       dummy: false,
-      marker: {row_marker: dead -9223372036854775767 0},
       tombstone: {row_tombstone: {tombstone: timestamp=-9223372036854775777, deletion_time=0}{shadowable tombstone: none}},
       position: {
         bound_weight: 0,
@@ -635,3 +634,4 @@
   ]
 }
 }
+test/boost/sstable_conforms_to_mutation_source_test.cc(0): Leaving test case "test_sstable_conforms_to_mutation_source"; testing time: 8631787us
```

**Comment by avikivity** [comment]
```
>>> print(hex(-9223372036854775767))
-0x7fffffffffffffd7
```
This is a very odd timestamp.

**Comment by bhalevy** [comment]
@tgrabiec I bisected the problem down to ecb6abe71714a48873d2cc80438660f21b5658a4 sstables: Dynamically adjust I/O size for index reads

With this change on top of it, for reproducing with `--random-seed=1869577008`
```diff
diff --git a/test/lib/mutation_source_test.cc b/test/lib/mutation_source_test.cc
index 5e8dbfc67..04d367c2b 100644
--- a/test/lib/mutation_source_test.cc
+++ b/test/lib/mutation_source_test.cc
@@ -562,7 +562,7 @@ static void test_streamed_mutation_forwarding_guarantees(populate_fn_ex populate
     }
 
     // Few random ranges
-    std::default_random_engine rnd;
+    auto& rnd = seastar::testing::local_random_engine;
     std::uniform_int_distribution<int> key_dist{0, n_keys - 1};
     for (int i = 0; i < 10; ++i) {
         std::vector<int> indices;
```

(This following change was needed for later changes in this series, merged in 9322c07c712967b3eb4c30f6955890e05932c655)
```diff
diff --git a/utils/cached_file.hh b/utils/cached_file.hh
index 6581cf851..ac8229a45 100644
--- a/utils/cached_file.hh
+++ b/utils/cached_file.hh
@@ -128,10 +128,9 @@ class cached_file {
                 page_idx_type start_page, offset_type start_offset_in_page)
             : _cached_file(&cf)
             , _pc(&pc)
-            , _trace_state(std::move(trace_state))
             , _page_idx(start_page)
             , _offset_in_page(start_offset_in_page)
-
+            , _trace_state(std::move(trace_state))
         { }
 
         // Yields the next chunk of data.
```

**Comment by tgrabiec** [comment]
Reproduced locally with 50dda795e93b4eda8564ef2cb490a4bf97485dd9. 

Reverting ecb6abe71714a48873d2cc80438660f21b5658a4 plus the following diff helps: 
```diff
--- a/sstables/index_reader.hh
+++ b/sstables/index_reader.hh
@@ -742,7 +742,7 @@ class index_reader {
         options.buffer_size = _sstable->sstable_buffer_size;
         options.read_ahead = 2;
         options.io_priority_class = pc;
-        options.dynamic_adjustments = _sstable->_index_history;
+//        options.dynamic_adjustments = _sstable->_index_history;
         return options;
     }
 
```

**Comment by avikivity** [comment]
Backported to 4.2, 4.3, 4.4. Although we never write ka/la sstables any more, it's better not to have code that writes sstables that are not compatible with Cassandra in the code base.

We should start removing the writer code for older formats.

**Comment by bhalevy** [comment]
> We should start removing the writer code for older formats.

https://github.com/scylladb/scylla/issues/8352
