### ISSUE TITLE
scylla_ntp_setup failed on amazon 2 linux distro

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#9393]
System under test
- ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-4.4/rpm/centos/2021-09-23T14:52:17Z/scylla.repo
- Actual aws image used: ami-099a8245f5daa82bf
- AWS region: eu-west-1
- Instance type: i3.large
- Scylla packages installed:
   - scylla-tools-4.4.5-0.20210923.01920c129.noarch
   - scylla-conf-4.4.5-0.20210923.01920c129.x86_64
   - scylla-python3-4.4.5-0.20210923.01920c129.x86_64
   - scylla-node-exporter-4.4.5-0.20210923.01920c129.x86_64
   - scylla-tools-core-4.4.5-0.20210923.01920c129.noarch
   - scylla-jmx-4.4.5-0.20210923.01920c129.noarch
   - scylla-server-4.4.5-0.20210923.01920c129.x86_64
   - scylla-kernel-conf-4.4.5-0.20210923.01920c129.x86_64
   - scylla-4.4.5-0.20210923.01920c129.x86_64

Job Amazon 2 aritifact test (https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/artifacts/job/artifacts-amazon2-test/79/execution/node/51) failed during setup stage with next error:
```
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Exit code: 1
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stdout:
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   Verifying  : ntpdate-4.2.8p15-3.amzn2.0.4.x86_64                          3/3 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Installed:
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   ntp.x86_64 0:4.2.8p15-3.amzn2.0.4    ntpdate.x86_64 0:4.2.8p15-3.amzn2.0.4   
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Dependency Installed:
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   autogen-libopts.x86_64 0:5.18.12-8.amzn2.0.1                                  
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Complete!
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > NTP setup failed.
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Stderr:
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > WARN  2021-09-27 09:45:29,079 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 124 MB: is less than recommended: 10 GB
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > INFO  2021-09-27 09:45:29,079 [shard 0] iotune - /var/tmp/mnt passed sanity checks
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >   File "/opt/scylladb/scripts/libexec/scylla_ntp_setup", line 98, in <module>
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  >     server = match.group(1)
16:45:39  < t:2021-09-27 09:45:34,199 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > AttributeError: 'NoneType' object has no attribute 'group'
```

Error happened only on linux amazon2. the error happened in code:
https://github.com/scylladb/scylla/blob/01920c1293c9460a7fca645460b9120c0c101611/dist/common/scripts/scylla_ntp_setup#L97

on instance with amazon2 linux version, /etc/ntp.conf doesn't contain server options. now it contain pool:
```
# Hosts on local network are less restricted.
#restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap

# Use public servers from the pool.ntp.org project.
# Please consider joining the pool (http://www.pool.ntp.org/join.html).
pool 2.amazon.pool.ntp.org iburst
```
this is a reason, why regexp failed to find the valid ntp server. the possible reason is that amazon update its image with amazon linux

output of distro like and version on amazon 2 linux:
```
[ec2-user@artifacts-amazon2-jenkins-db-node-eb0fa0d0-1 bin]$ ./python3
Python 3.9.0 (default, Oct  6 2020, 00:00:00) 
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distro
>>> 
>>> 
>>> distro.like()
'centos rhel fedora'
>>> distro.version()
'2'
>>> 

```

**Comment by aleksbykov** [comment]
FYI @yaronkaikov

**Comment by syuu1228** [comment]
We already fixed this at 735c83b27fcc613a31b7c7011bd02e86b71e737a, but it heavily modified the scirpt too much, not able to backport to 4.4 (4.5 does not affected this, since it force using chrony).
We probably need to write new patch for 4.4 and 2020.1.

**Comment by slivne** [comment]
does this work with 4.4.4 ? - is this a regression ?

**Comment by yaronkaikov** [comment]
@slivne Yes, it's worked in 4.4.4 - https://docs.google.com/document/d/1WMG2Pqv6TOKWkPh2CeJViwj-6b7Fs6HablhZEc8WoA8/edit

**Comment by slivne** [comment]
fixed
